"""Signed forwarding header for router → backend operator-identity carry.

Part of the **retire-system-token** plan, Wave 1. After Wave 1 the
backend's :class:`AuthHeaderMiddleware` no longer accepts the
``g.system_token`` as a god-key bearer; the only two ways into a
sensitive backend route are (a) a per-agent bearer token that matches
a row in the ``agents`` table, or (b) a signed forwarding header
generated by a trusted router process holding the per-project HMAC
key.

Format
------

The header value is four dot-separated fields::

    <operator_id>.<role>.<expiry-unix-seconds>.<HMAC-hex>

* ``operator_id`` — opaque string identifying the operator (the
  dashboard's logged-in user). The backend stamps this onto
  ``g.current_operator`` so audit logs can attribute the action.
* ``role`` — the operator's *real* per-project role, drawn from the
  known project-role set (``operator`` / ``viewer``). The router
  resolves this from ``project_membership`` (via
  ``group_resolver.resolve_user_project_role``) and signs it; the
  backend parses it back onto ``Principal.project_role`` so
  :func:`resolve_capabilities` yields the caller's *actual*
  capability bundle. This field is the fix for the viewer→operator
  escalation (SEC-1): the pre-fix backend hard-coded
  ``project_role="operator"`` for every verified header, so a
  viewer-tier operator got the full operator bundle over the MCP
  wire. The role is HMAC-covered, so it can't be tampered in flight,
  and an unknown role value fails ``verify`` (hard reject).
* ``expiry-unix-seconds`` — integer-seconds-since-epoch after which
  the backend rejects the header. The router-side ``sign`` helper
  defaults to ``now + 30 s``; the backend's ``verify`` helper also
  enforces a freshness window (the header MUST NOT claim an expiry
  more than ``replay_window_sec`` in the future, so a stolen header
  with a year-long expiry is rejected).
* ``HMAC-hex`` — lowercase hex HMAC-SHA256 over the literal string
  ``f"{operator_id}.{role}.{expiry}"`` keyed by the per-project HMAC
  key. Note that the HMAC input does NOT include the trailing
  ``.<hmac>`` — that would be circular.

Key material
------------

* 32 bytes (256 bits) of ``os.urandom``.
* Wave 3 will wire the launcher to write the key file at backend
  spawn and pass the path via ``--forwarding-hmac-in``. Wave 1 ships
  only the read side (``server_bootstrap.bootstrap_server`` loads
  the file if the flag is set and stamps ``g.forwarding_hmac_key``).
* Wave 1 dormant fallback: if ``g.forwarding_hmac_key`` is ``None``
  (no key file present yet — Wave 2/3 hasn't shipped the launcher
  write side), the middleware silently ignores the forwarding header
  and falls back to the agents-table bearer path. Tests that need
  the forwarding-header path explicitly populate the key globally.

Replay window
-------------

``verify`` rejects any header whose ``expiry`` is more than
``replay_window_sec`` seconds in the future (default 30 s). This
defends against an attacker who captured a header with an
attacker-chosen, far-future expiry. The router-side ``sign`` defaults
match the verify window so a legitimately-signed header always
passes the replay check when verified promptly.

Why not just include a nonce
----------------------------

We considered a nonce + per-project replay cache to give one-shot
header semantics, but the deployment shape doesn't justify it: the
router and backend are co-located (same machine, Unix-domain socket),
the request lifetime is < 1 s, and a stolen header from a
co-located process means the attacker already owns the host. The
30-second window is the right trade-off.
"""

from __future__ import annotations

import hashlib
import hmac
import time
from typing import Optional


__all__ = ["HEADER_NAME", "VALID_ROLES", "sign", "verify"]


#: HTTP header name the router uses to carry the signed token. Kept
#: as a module constant so the middleware + the test suite reference
#: the same string and a future rename is one edit.
HEADER_NAME = "X-Agent-MCP-Forwarded-Operator"


#: The known per-project role vocabulary the forwarding header may
#: carry. Kept in lock-step with ``project_membership.role`` (the
#: router's ``group_resolver.resolve_user_project_role`` only ever
#: returns one of these) and with
#: :data:`agent_mcp.core.capabilities.PROJECT_ROLE_BUNDLES`. ``sign``
#: refuses to mint a header for a role outside this set and ``verify``
#: hard-rejects (returns ``None``) an unknown role — an unrecognised
#: role must never silently collapse to a broad capability bundle.
VALID_ROLES: frozenset[str] = frozenset({"operator", "viewer"})


#: Default lifetime for a freshly-signed header. The router's request
#: hops one Unix-domain socket; 30 seconds is plenty for the wire +
#: backend processing. Shorter is safer against capture-and-replay
#: but doesn't change the qualitative threat model (see module
#: docstring).
_DEFAULT_TTL_SEC: int = 30

#: Default replay window the verifier enforces. The verifier rejects
#: any header whose ``expiry`` is more than this many seconds in the
#: future at verify time — so a header signed with a 1-year TTL by a
#: cooperative but bug-introducing router would still be rejected.
_DEFAULT_REPLAY_WINDOW_SEC: int = 30


def _hmac_hex(operator_id: str, role: str, expiry: int, key: bytes) -> str:
    """Compute the HMAC-SHA256 over ``f"{operator_id}.{role}.{expiry}"``.

    Extracted so sign + verify use exactly the same input shape;
    a single source of truth for "what does the HMAC cover". The
    ``role`` is inside the MAC so a man-in-the-middle can't rewrite a
    ``viewer`` header into an ``operator`` one without the key.
    """
    message = f"{operator_id}.{role}.{expiry}".encode("utf-8")
    digest = hmac.new(key, message, hashlib.sha256).hexdigest()
    return digest


def sign(
    operator_id: str,
    role: str,
    key: bytes,
    ttl_sec: int = _DEFAULT_TTL_SEC,
    *,
    _now: Optional[int] = None,
) -> str:
    """Produce a signed forwarding-header value.

    Parameters
    ----------
    operator_id:
        Opaque operator identifier; whatever the router-side cookie
        validation resolved the session to. Must be non-empty and
        contain no dot characters (the dot is the field separator;
        an operator-id with a dot would be unparseable on the verify
        side and indicate a deeper input-validation bug).
    role:
        The operator's *real* per-project role — one of
        :data:`VALID_ROLES` (``operator`` / ``viewer``). The router
        MUST pass the value it resolved from ``project_membership``,
        NOT a fixed ``"operator"``: signing a fixed role is exactly
        the SEC-1 escalation this parameter closes. A role outside
        :data:`VALID_ROLES` is a programmer error and raises.
    key:
        Raw HMAC key bytes. The caller is responsible for sourcing
        these (per-project file written by the launcher).
    ttl_sec:
        How many seconds from now the header should remain valid.
        Defaults to :data:`_DEFAULT_TTL_SEC`.
    _now:
        Test seam — pass an integer to pin the "current time" the
        signer uses. Production callers should leave this unset.

    Returns
    -------
    A ``"<operator_id>.<role>.<expiry>.<hex-hmac>"`` string ready to
    drop into the :data:`HEADER_NAME` HTTP header.
    """
    if not operator_id:
        raise ValueError("operator_id must be non-empty")
    if "." in operator_id:
        raise ValueError(
            "operator_id must not contain '.' (header field separator)"
        )
    if role not in VALID_ROLES:
        raise ValueError(
            f"role must be one of {sorted(VALID_ROLES)}; got {role!r}"
        )
    if not key:
        raise ValueError("key must be non-empty bytes")
    if ttl_sec <= 0:
        raise ValueError("ttl_sec must be positive")

    now = int(_now) if _now is not None else int(time.time())
    expiry = now + int(ttl_sec)
    mac = _hmac_hex(operator_id, role, expiry, key)
    return f"{operator_id}.{role}.{expiry}.{mac}"


def verify(
    header_value: str,
    key: bytes,
    replay_window_sec: int = _DEFAULT_REPLAY_WINDOW_SEC,
    *,
    _now: Optional[int] = None,
) -> Optional[tuple[str, str]]:
    """Validate a forwarding-header value; return (operator_id, role).

    Returns ``None`` on ANY verification failure — malformed, wrong
    HMAC, expired, replay-window-violating, or an unknown ``role``.
    Callers MUST treat a ``None`` return as "reject this request"
    without falling through to a different auth mode (otherwise a
    tampered header could shadow the bearer-token path).

    Parameters
    ----------
    header_value:
        The raw HTTP header value. Whitespace is NOT stripped here —
        the middleware is expected to feed the verbatim value.
    key:
        Raw HMAC key bytes; same key the router used to sign.
    replay_window_sec:
        Reject any header whose claimed expiry is more than this many
        seconds in the future of ``_now`` (or wall-clock time).
        Defends against signed-with-far-future-expiry abuse.
    _now:
        Test seam — pass an integer to pin "current time" during
        verification. Production callers leave this unset.

    Returns
    -------
    The ``(operator_id, role)`` pair parsed out of the header on
    success, else ``None``. ``role`` is guaranteed to be a member of
    :data:`VALID_ROLES`.
    """
    if not header_value or not key:
        return None
    if not isinstance(header_value, str):  # pragma: no cover - defensive
        return None

    parts = header_value.split(".")
    # Exactly four fields (operator_id, role, expiry, mac). A dot in
    # the operator_id at sign time was already rejected; on the verify
    # side an unexpected dot count is a malformed header.
    if len(parts) != 4:
        return None
    operator_id, role, expiry_str, presented_mac = parts
    if not operator_id or not role or not expiry_str or not presented_mac:
        return None

    # Unknown role → hard reject. This is the SEC-1 defence: a role we
    # don't recognise must never reach ``resolve_capabilities`` (where
    # an unexpected value could, in the worst case, be mishandled into
    # a broad grant). Validate BEFORE the constant-time MAC compare so
    # a forged role is rejected regardless of MAC.
    if role not in VALID_ROLES:
        return None

    try:
        expiry = int(expiry_str)
    except ValueError:
        return None

    now = int(_now) if _now is not None else int(time.time())

    # Freshness: header must not have already expired.
    if expiry <= now:
        return None

    # Replay window: header must not claim a far-future expiry. A
    # legitimate router with a bug (TTL=1y) or a captured-then-replayed
    # header with an extended TTL both get rejected here.
    if expiry - now > int(replay_window_sec):
        return None

    expected_mac = _hmac_hex(operator_id, role, expiry, key)

    # Constant-time compare — guard against timing-side-channel
    # discovery of valid HMAC prefixes. ``hmac.compare_digest`` is the
    # stdlib's portable constant-time check.
    if not hmac.compare_digest(expected_mac, presented_mac):
        return None

    return operator_id, role
