// DO NOT EDIT BY HAND.
//
// This file is generated by `scripts/generate_ts_types.py` from the
// Pydantic mirrors in `agent_mcp/db/pydantic_mirrors.py`. The CI
// step `tests/test_orm_is_source_of_truth.py::
// test_ts_type_generator_is_deterministic` enforces a clean diff
// on every PR.
//
// To add or change a field:
//
//   1. Update the SQLAlchemy model in `agent_mcp/db/models/`.
//   2. Update the Pydantic mirror in `agent_mcp/db/pydantic_mirrors.py`.
//   3. Run `python scripts/generate_ts_types.py` and commit the diff.
//
// The dashboard imports the interfaces declared here from
// `lib/api.ts`, which re-exports them under their canonical names
// (Agent, Task, ...).


/** Pydantic mirror of the `agent_actions` table. */
export interface AgentActionMirror {
  action_id: number
  agent_id: string
  action_type: string
  task_id?: string | null
  timestamp: string
  details?: string | null
}

/** Pydantic mirror of the `agent_messages` table. */
export interface AgentMessageMirror {
  message_id: string
  sender_id: string
  recipient_id: string
  message_content: string
  message_type: string
  priority: string
  timestamp: string
  delivered: boolean
  read: boolean
  subject?: string | null
  parent_message_id?: string | null
}

/** Pydantic mirror of the `agents` table. */
export interface AgentMirror {
  token: string
  agent_id: string
  created_at: string
  status: string
  current_task?: string | null
  working_directory: string
  color?: string | null
  terminated_at?: string | null
  updated_at?: string | null
  aoe_session_id?: string | null
  auto_event_loop?: boolean | null
  last_event_seen_at?: string | null
  last_activity_at?: string | null
  agent_role?: string | null
  profile?: string | null
  profile_updated_at?: string | null
  profile_reviewed_at?: string | null
  profile_updated_by?: string | null
}

/** Pydantic mirror of the `claude_code_sessions` table. */
export interface ClaudeCodeSessionMirror {
  session_id: string
  pid: number
  parent_pid: number
  first_detected: string
  last_activity: string
  working_directory?: string | null
  agent_id?: string | null
  status?: string | null
  git_commits?: string | null
  metadata?: string | null
}

/** Pydantic mirror of the `file_metadata` table. */
export interface FileMetadataMirror {
  filepath: string
  metadata: string
  last_updated: string
  updated_by: string
  content_hash?: string | null
}

/** Pydantic mirror of the `mcp_sessions` table. */
export interface McpSessionMirror {
  session_id: string
  agent_id: string
  opened_at: string
  last_seen_at: string
  bearer_token_hash: string
  alias_used?: string | null
}

/** Pydantic mirror of the `pending_directive` table. */
export interface PendingDirectiveMirror {
  poke_id: string
  agent_id: string
  prompt: string
  priority?: string | null
  created_at: string
  created_by?: string | null
  delivered_at?: string | null
}

/** Pydantic mirror of the `project_context` table. */
export interface ProjectContextMirror {
  context_key: string
  value: string
  description?: string | null
  created_at?: string | null
  created_by?: string | null
  updated_at: string
  updated_by: string
}

/** Pydantic mirror of the `project_settings` table. */
export interface ProjectSettingsMirror {
  context_key: string
  value: string
  description?: string | null
  created_at?: string | null
  created_by?: string | null
  updated_at: string
  updated_by: string
}

/** Pydantic mirror of the `rag_chunks` table. */
export interface RagChunkMirror {
  chunk_id: number
  source_type: string
  source_ref: string
  chunk_text: string
  indexed_at: string
  metadata?: string | null
}

/** Pydantic mirror of the `rag_meta` table. */
export interface RagMetaMirror {
  meta_key: string
  meta_value?: string | null
}

/** Pydantic mirror of the `scheduled_directive` table. */
export interface ScheduledDirectiveMirror {
  directive_id: string
  agent_id: string
  prompt: string
  interval_seconds: number
  next_due_at: string
  enabled?: number | null
  status?: string | null
  until_at?: string | null
  max_runs?: number | null
  run_count?: number | null
  created_at: string
  created_by?: string | null
  updated_at?: string | null
  updated_by?: string | null
}

/** Pydantic mirror of the `task_notes` table. */
export interface TaskNoteMirror {
  note_id: number
  task_id: string
  author?: string | null
  timestamp: string
  text: string
}

/** Pydantic mirror of the `tasks` table. */
export interface TaskMirror {
  task_id: string
  title: string
  description?: string | null
  assigned_to?: string | null
  created_by: string
  status: string
  priority: string
  created_at: string
  updated_at: string
  parent_task?: string | null
  child_tasks?: string | null
  depends_on_tasks?: string | null
  notes?: string | null
}

/** Table-name to interface map. */
export const MIRROR_TABLE_NAMES = [
  "agent_actions",
  "agent_messages",
  "agents",
  "claude_code_sessions",
  "file_metadata",
  "mcp_sessions",
  "pending_directive",
  "project_context",
  "project_settings",
  "rag_chunks",
  "rag_meta",
  "scheduled_directive",
  "task_notes",
  "tasks",
] as const;
