# pkgs.nixosTest: end-to-end smoke for PR-2 event-coord wake loop.
#
# Boots a single-node VM with the multi-tenant router + per-project
# backend template (same shape as multi-tenant.nix), then drives the
# `wait_for_events` + `fetch_events_since` MCP tools via curl with two
# distinct bearer tokens representing two simulated agents.
#
# Test plan covers the 10 cases from the prancy-napping-pie locked
# plan's "E2E verification on the VM" section:
#
#   1. serverInfo.instructions wake-loop bootstrap appears when both
#      flags ON; disappears when per-agent flag OFF.
#   2. wait_for_events blocks then returns on inbox message (fat).
#   6. fetch_events_since catch-up.
#   7. Concurrent wait_for_events → conflict envelope.
#   8. stop_listening on per-agent flag flip.
#   9. assign_task creates a ROOT task (structured capability-tag routing
#      retired in migration 0019 / ADR-0019 — unassigned tasks now notify
#      every agent unconditionally, so cases 3/4/5 no longer apply).
#   10. Global toggle OFF → stop_listening for all agents.
#
# Test runtime target: ~2-3 minutes total once the VM is booted.
{ pkgs, lib, self, ... }:

let
  ports = import ./_ports.nix;
  packagedPkgs = import ../packages.nix {
    inherit pkgs lib;
    src = self;
  };
in
pkgs.testers.nixosTest {
  name = "agent-mcp-event-driven-coord";

  nodes.machine = { config, pkgs, ... }: {
    imports = [ ./fake-openai.nix ];

    virtualisation = {
      memorySize = 1536;
      cores = 2;
      diskSize = 2048;
    };

    users.users.testuser = {
      isNormalUser = true;
      group = "testuser";
      uid = 1500;
      createHome = true;
    };
    users.groups.testuser = {};

    systemd.services."agent-mcp@" = {
      description = "Agent-MCP backend — project %i";
      after = [ "fake-openai.service" ];
      serviceConfig = {
        Type = "simple";
        User = "testuser";
        Group = "testuser";
        Environment = [
          "HOME=/home/testuser"
          "XDG_RUNTIME_DIR=/run/user/1500"
          "OPENAI_BASE_URL=http://127.0.0.1:11434/v1"
          "OPENAI_API_KEY=fake"
          "AGENT_MCP_EMBEDDING_MODEL=fake-zero-vector"
          "AGENT_MCP_EMBEDDING_DIMENSION=1024"
          # Keep the wake-loop default snappy so the
          # `wait_for_events(timeout=10)` calls in the test don't
          # blow past the polkit-managed unit's grace period.
          "AGENT_MCP_EVENT_WAIT_TIMEOUT=60"
          # Launcher / router share this for socket path discovery.
          # In the VM test we use the systemd RuntimeDirectory at
          # /run/agent-mcp (created with 0700 perms below) instead
          # of XDG_RUNTIME_DIR which testuser can't write to.
          "AGENT_MCP_SOCK_DIR=/run/agent-mcp"
          # The launcher resolves the project workspace from this file.
          # The HOME-based fallback ($HOME/.config/agent-mcp/…) already
          # matches, but pin it explicitly for parity with the other VM
          # templates (no-auto-cleanup / production module.nix).
          "AGENT_MCP_PROJECTS_FILE=/home/testuser/.config/agent-mcp/projects.local.json"
        ];
        RuntimeDirectory = "agent-mcp/%i";
        RuntimeDirectoryMode = "0700";
        # F015 v4 (see nix/module.nix): the per-project forwarding-HMAC
        # key is generated by the unit's ExecStartPre, and the backend's
        # ``--forwarding-hmac-in`` (which the launcher always passes) is
        # click-validated with ``exists=True`` — it refuses to start if
        # the file is absent, exiting 2/INVALIDARGUMENT on every launch.
        # Generate it here (idempotently) before clearing the stale
        # socket, exactly as no-auto-cleanup.nix and the production
        # template do; this test template previously did only the socket
        # cleanup, so the backend never came up (the pre-existing
        # failure).
        ExecStartPre = [
          "${pkgs.runtimeShell} -c 'test -f \"$RUNTIME_DIRECTORY/forwarding_hmac\" || { ${pkgs.coreutils}/bin/head -c 32 /dev/urandom > \"$RUNTIME_DIRECTORY/forwarding_hmac\" && ${pkgs.coreutils}/bin/chmod 600 \"$RUNTIME_DIRECTORY/forwarding_hmac\"; }'"
          "${pkgs.coreutils}/bin/rm -f /run/agent-mcp/%i/backend.sock"
        ];
        ExecStart = ''
          ${packagedPkgs.agentMcpLauncher}/bin/agent-mcp-launcher %i
        '';
        Restart = "on-failure";
        RestartSec = 5;
      };
    };

    systemd.services.agent-mcp-router = {
      description = "Agent-MCP router (event-coord test)";
      wantedBy = [ "multi-user.target" ];
      after = [ "fake-openai.service" "network.target" ];
      environment = {
        AGENT_MCP_PROJECTS_FILE = "/home/testuser/.config/agent-mcp/projects.local.json";
        # Phase 1 PR B (prancy-napping-pie): see multi-tenant.nix.
        AGENT_MCP_ROUTER_DB = "/home/testuser/.config/agent-mcp/router.db";
        # Phase 1 PR C: see single-tenant.nix.
        AGENT_MCP_BOOTSTRAP_USERNAME = "ci-sentinel";
        AGENT_MCP_BOOTSTRAP_PASSWORD = "ci-sentinel-pw";
        AGENT_MCP_SOCK_DIR = "/run/agent-mcp";
        AGENT_MCP_DASHBOARD_DIR = "${packagedPkgs.agentMcpDashboard}/share/agent-mcp-dashboard";
        AGENT_MCP_EXTERNAL_URL = "http://localhost:${toString ports.routerPort}";
        AGENT_MCP_DEFAULT_WORKSPACE = "/home/testuser/projects";
        AGENT_MCP_ROUTER_PORT = toString ports.routerPort;
        AGENT_MCP_ROUTER_HOST = "0.0.0.0";
        AGENT_MCP_IDLE_SEC = "14400";
        AGENT_MCP_README_HTML = "${packagedPkgs.readmeHtml}";
        AGENT_MCP_INSTALLER_TEMPLATE = "${packagedPkgs.installerTemplate}";
        # The router defaults to `systemctl --user`, which matches
        # the nixos-developer-system home-manager deployment. In the
        # VM test the agent-mcp@%i template is system-level, so flip
        # the mode (mirrors nix/module.nix's setting for the home-
        # manager system-mode deployment path).
        AGENT_MCP_SYSTEMCTL_MODE = "system";
      };
      serviceConfig = {
        Type = "simple";
        User = "testuser";
        Group = "testuser";
        RuntimeDirectory = "agent-mcp";
        RuntimeDirectoryMode = "0700";
        ExecStartPre = "${pkgs.coreutils}/bin/mkdir -p /home/testuser/.config/agent-mcp /home/testuser/projects";
        ExecStart = "${packagedPkgs.agentMcpRouterWrapper}/bin/agent-mcp-router";
        Restart = "on-failure";
        RestartSec = 5;
      };
    };

    security.polkit.enable = true;
    security.polkit.extraConfig = ''
      polkit.addRule(function(action, subject) {
        if (action.id == "org.freedesktop.systemd1.manage-units" &&
            subject.user == "testuser") {
          var unit = action.lookup("unit");
          if (unit && (unit.indexOf("agent-mcp@") == 0)) {
            return polkit.Result.YES;
          }
        }
      });
    '';

    environment.systemPackages = [ pkgs.curl pkgs.jq pkgs.sqlite ];
    networking.firewall.enable = false;
  };

  testScript = ''
    import json

    start_all()
    machine.wait_for_unit("fake-openai.service")
    machine.wait_for_unit("agent-mcp-router.service")
    machine.wait_for_open_port(${toString ports.routerPort})

    # ── Bootstrap the project ────────────────────────────────────
    # Log in the sentinel operator (ADR 0014: admin REST surface is
    # session-gated) and create the project via the REST resource.
    machine.succeed(
        "curl -fsS -c /tmp/agent-mcp-cookies.txt "
        "-F username=ci-sentinel -F password=ci-sentinel-pw "
        "http://127.0.0.1:${toString ports.routerPort}/agent-mcp/login"
    )
    machine.succeed(
        "curl -fsSL -b /tmp/agent-mcp-cookies.txt -o /dev/null "
        "-H 'Accept: application/vnd.agent-mcp.v1+json' "
        "-H 'Content-Type: application/json' "
        "-X POST --data '{\"name\": \"coord-test\"}' "
        "http://127.0.0.1:${toString ports.routerPort}/agent-mcp/api/router/projects"
    )

    # Start the per-project backend explicitly. The router would
    # lazy-spawn on the first /mcp request, but starting directly
    # gives us a deterministic readiness probe (wait_for_unit).
    machine.succeed("systemctl start agent-mcp@coord-test.service")
    machine.wait_for_unit("agent-mcp@coord-test.service")

    # Poll the backend's DB file until it exists (the unit's
    # "active" state can precede DB initialisation). The workspace
    # path is what the create handler wrote to projects.local.json,
    # which is AGENT_MCP_DEFAULT_WORKSPACE / <name> =
    # /home/testuser/projects/coord-test.
    db_path = "/home/testuser/projects/coord-test/.agent/mcp_state.db"
    machine.wait_until_succeeds(f"test -f {db_path}", timeout=60)

    # Stop the backend before SQL inserts: the backend holds the
    # sqlite file with WAL mode and SQLITE_BUSY errors otherwise.
    # The wait_until_succeeds restart-trigger curl earlier in the
    # test confirms it boots cleanly; we restart it again after the
    # SQL seed completes.
    machine.succeed("systemctl stop agent-mcp@coord-test.service")

    # ── Provision two agents directly via SQL ────────────────────
    # The harness pattern from existing VM tests: skip the
    # create_agent tool and INSERT directly so we control the token
    # and agent_role precisely.
    def sql(stmt: str) -> str:
        # `sqlite3` defaults to no row separator for SELECT; the
        # test driver expects plain stdout, so we just shell out.
        return machine.succeed(f"sqlite3 {db_path} \"{stmt}\"")

    sql(
        "INSERT INTO agents (token, agent_id, "
        "created_at, status, working_directory, color, updated_at, "
        "auto_event_loop) VALUES "
        "('tokbe', 'worker-backend', "
        " '2026-01-01T00:00:00', 'active', '/tmp', '#888', "
        " '2026-01-01T00:00:00', 1)"
    )
    sql(
        "INSERT INTO agents (token, agent_id, "
        "created_at, status, working_directory, color, updated_at, "
        "auto_event_loop) VALUES "
        "('tokfe', 'worker-frontend', "
        " '2026-01-01T00:00:00', 'active', '/tmp', '#888', "
        " '2026-01-01T00:00:00', 1)"
    )
    # Seed a manager agent — Test 9 creates a ROOT task via assign_task,
    # which workers can't do (they must file under a parent_task_id).
    # agent_role is set here so it hydrates as manager at backend startup.
    sql(
        "INSERT INTO agents (token, agent_id, "
        "created_at, status, working_directory, color, updated_at, "
        "auto_event_loop, agent_role) VALUES "
        "('tokmgr', 'mgr-norm', "
        " '2026-01-01T00:00:00', 'active', '/tmp', '#888', "
        " '2026-01-01T00:00:00', 1, 'manager')"
    )

    # Enable worker-to-worker messaging. config_allow_worker_to_worker
    # defaults OFF (the worker-policy security default); without this,
    # Test 6's worker-backend → worker-backend self-message is denied by
    # the send-message gate, so no message event is published and
    # fetch_events_since returns empty. The gate reads this live per-call
    # (tools/access._get_config_bool), so no restart is needed — but we
    # seed it here in the backend-stopped SQL window alongside the agents.
    # ADR-0016 (Wave 11): config_* rows live in project_settings.
    sql(
        "INSERT INTO project_settings (context_key, value, description, "
        "created_at, created_by, updated_at, updated_by) VALUES "
        "('config_allow_worker_to_worker', 'true', 'wkr-policy seed', "
        " '2026-01-01T00:00:00', 'vm-test', "
        " '2026-01-01T00:00:00', 'vm-test')"
    )

    # The auth allow-list is loaded at backend startup; restart so
    # the two newly-inserted tokens are accepted.
    machine.succeed("systemctl restart agent-mcp@coord-test.service")
    machine.wait_for_unit("agent-mcp@coord-test.service")
    # The router caches /api/tokens for 3s; sleep a bit longer so
    # the next /mcp request triggers a fresh fetch that includes
    # the newly-inserted agents.
    machine.sleep(5)
    # Seed an initialize JSON body to disk and curl it; avoids the
    # double-shell-escape minefield of inlining JSON in nix → python →
    # bash.
    machine.succeed(
        "echo '{\"jsonrpc\":\"2.0\",\"id\":1,"
        "\"method\":\"initialize\","
        "\"params\":{\"protocolVersion\":\"2025-03-26\","
        "\"capabilities\":{},"
        "\"clientInfo\":{\"name\":\"vm-test\",\"version\":\"0\"}}}' "
        "> /tmp/init.json"
    )
    # The backend is healthy when the MCP transport accepts an
    # initialize request without 503/401.
    machine.wait_until_succeeds(
        "curl -fsS -o /dev/null -X POST "
        " -H 'Authorization: Bearer tokbe' "
        " -H 'Content-Type: application/json' "
        " -H 'Accept: application/json, text/event-stream' "
        " --data @/tmp/init.json "
        "http://127.0.0.1:${toString ports.routerPort}/agent-mcp/mcp/coord-test",
        timeout=60,
    )

    MCP_URL = (
        "http://127.0.0.1:${toString ports.routerPort}"
        "/agent-mcp/mcp/coord-test"
    )

    def mcp_call(token: str, method: str, params: dict, jid: int = 1) -> dict:
        body = json.dumps({
            "jsonrpc": "2.0", "id": jid,
            "method": method, "params": params,
        })
        # Write JSON to a tmpfile to avoid the nix → python → bash
        # double-escape minefield. curl reads via --data @file.
        machine.succeed(
            "cat > /tmp/mcp-body.json <<'JSONBODY'\n"
            + body + "\nJSONBODY"
        )
        out = machine.succeed(
            f"curl -fsS -X POST "
            f"-H 'Authorization: Bearer {token}' "
            f"-H 'Content-Type: application/json' "
            f"-H 'Accept: application/json, text/event-stream' "
            f"--data @/tmp/mcp-body.json {MCP_URL}"
        )
        # When the server replies with SSE, the JSON body is on a
        # `data:` line. Strip that prefix uniformly.
        for line in out.splitlines():
            line = line.strip()
            if line.startswith("data:"):
                return json.loads(line[5:].strip())
        return json.loads(out)

    def tool_call(token: str, name: str, args: dict) -> dict:
        """Return the parsed tool-result text envelope.

        Some tools return a JSON envelope in the text content
        (``fetch_events_since``, ``wait_for_events`` — the ones this
        test asserts structured fields on); others return a
        human-readable confirmation string (``send_agent_message`` →
        "Message sent to …", ``assign_task`` → a summary line) that is
        NOT JSON. Those are only used here as setup steps whose return
        value is ignored, so fall back to wrapping the raw text rather
        than raising ``JSONDecodeError`` — the structured-envelope tools
        still parse exactly as before.
        """
        rsp = mcp_call(token, "tools/call", {
            "name": name, "arguments": args,
        })
        result = rsp.get("result", {})
        content = result.get("content", [])
        if not content:
            return {}
        text = content[0].get("text", "{}")
        try:
            return json.loads(text)
        except (json.JSONDecodeError, TypeError):
            return {"_text": text}

    # ── Test 1: serverInfo.instructions wake-loop bootstrap ──────
    init = mcp_call("tokbe", "initialize", {
        "protocolVersion": "2025-03-26",
        "capabilities": {},
        "clientInfo": {"name": "vm-test", "version": "0"},
    })
    instr = init.get("result", {}).get("instructions") or ""
    assert "wait_for_events" in instr, (
        f"wake-loop bootstrap missing from initialize response; got: {instr!r}"
    )

    # Flip per-agent flag OFF; bootstrap should disappear.
    sql("UPDATE agents SET auto_event_loop = 0 WHERE agent_id = 'worker-backend'")
    init = mcp_call("tokbe", "initialize", {
        "protocolVersion": "2025-03-26",
        "capabilities": {},
        "clientInfo": {"name": "vm-test", "version": "0"},
    })
    instr = init.get("result", {}).get("instructions") or ""
    assert "wait_for_events" not in instr, (
        f"wake-loop bootstrap should NOT appear when per-agent flag OFF; got: {instr!r}"
    )
    # Restore.
    sql("UPDATE agents SET auto_event_loop = 1 WHERE agent_id = 'worker-backend'")

    # ── Test 6: fetch_events_since catch-up (the simplest path) ──
    # worker-frontend sends a message to worker-backend, then
    # worker-backend calls fetch_events_since and expects the received
    # message event in the catch-up envelope. NOTE: the sender must be a
    # DIFFERENT agent (self-communication is denied), and worker→worker
    # messaging requires config_allow_worker_to_worker=true (seeded
    # above) — otherwise the send is denied and no event is published.
    tool_call("tokfe", "send_agent_message", {
        "recipient_id": "worker-backend",
        "message": "catch up test",
        "deliver_method": "store",
    })
    env = tool_call("tokbe", "fetch_events_since", {})
    assert env.get("events"), f"fetch_events_since: no events; got {env}"
    assert env.get("cursor"), f"fetch_events_since: no cursor; got {env}"

    # ── Test 8: stop_listening on per-agent flag flip ────────────
    # Flip OFF then call wait_for_events — should return immediately.
    sql("UPDATE agents SET auto_event_loop = 0 WHERE agent_id = 'worker-backend'")
    env = tool_call("tokbe", "wait_for_events", {"timeout_seconds": 30})
    events = env.get("events", [])
    assert any(e.get("type") == "stop_listening" for e in events), (
        f"expected stop_listening when per-agent flag OFF; got {env}"
    )
    sql("UPDATE agents SET auto_event_loop = 1 WHERE agent_id = 'worker-backend'")

    # ── Test 10: global toggle OFF → stop_listening for everyone ──
    # ADR-0016 (Wave 11): the loop toggle lives in project_settings.
    sql(
        "INSERT OR REPLACE INTO project_settings "
        "(context_key, value, created_at, updated_at, "
        " created_by, updated_by) VALUES "
        "('config_auto_event_loop_global', 'false', "
        " '2026-01-01T00:00:00', '2026-01-01T00:00:00', "
        " 'admin', 'admin')"
    )
    env_be = tool_call("tokbe", "wait_for_events", {"timeout_seconds": 30})
    env_fe = tool_call("tokfe", "wait_for_events", {"timeout_seconds": 30})
    for who, env in (("be", env_be), ("fe", env_fe)):
        assert any(
            e.get("type") == "stop_listening" for e in env.get("events", [])
        ), f"{who}: expected stop_listening when global flag OFF; got {env}"
    sql(
        "UPDATE project_settings SET value = 'true' "
        "WHERE context_key = 'config_auto_event_loop_global'"
    )

    # ── Test 9: assign_task creates a ROOT task (no capability tags) ──
    # The structured capability-tag routing was retired (migration 0019,
    # ADR-0019): there is no longer a `required_capabilities` column and
    # unassigned tasks notify every agent unconditionally. This test just
    # verifies a manager can still create a ROOT task via assign_task.
    # Workers cannot create ROOT tasks (must specify parent_task_id), so
    # use the seeded manager agent (mgr-norm / tokmgr) — agent_role is
    # hydrated into the backend's active-agent set at startup, so the
    # manager must be seeded before the backend restart above.
    tool_call("tokmgr", "assign_task", {
        "task_title": "root task no-caps",
        "task_description": "x",
    })
    cnt = sql(
        "SELECT COUNT(*) FROM tasks WHERE title = 'root task no-caps'"
    ).strip()
    assert cnt == "1", (
        f"assign_task should create the root task; got count={cnt!r}"
    )

    # Smoke summary print so a failed assertion is easy to spot in
    # the test log.
    print("event-driven-coord VM test: all assertions passed")
  '';
}
