#!/usr/bin/env python3
"""Generate TypeScript types from the Pydantic mirrors (PR-W3).

Walks `agent_mcp.db.pydantic_mirrors.MIRRORS` and emits one
TypeScript interface per mirror to
`agent_mcp/dashboard/lib/api-types.generated.ts` (or a
`--output`-supplied path).

Determinism guarantee
---------------------

* Mirrors iterate in alphabetical table-name order (already enforced
  by the `MIRRORS` registry).
* Each interface emits its fields in `model_fields` declaration
  order, which is itself stable (Pydantic preserves declaration
  order).
* No timestamps or version strings get baked into the output.

Two consecutive runs produce byte-identical output. The invariant
test `tests/test_orm_is_source_of_truth.py::
test_ts_type_generator_is_deterministic` enforces this in CI.

Why hand-rolled, not `datamodel-codegen`
----------------------------------------

The plan accepted a hand-rolled fallback explicitly:

> If you hit a wall on the TS generator (datamodel-codegen
> non-deterministic, etc), fall back to a hand-rolled generator
> that just walks Pydantic `model_json_schema()` and emits TS
> interfaces directly.

We took that fallback. The Pydantic v2 `model_json_schema()` is
deterministic, ships with the SDK we already depend on, and the
output shape is small enough that a 100-line walker covers it
without any new dependency.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

# Make the package importable when invoked from the repo root.
REPO_ROOT = Path(__file__).resolve().parent.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))


HEADER = """\
// DO NOT EDIT BY HAND.
//
// This file is generated by `scripts/generate_ts_types.py` from the
// Pydantic mirrors in `agent_mcp/db/pydantic_mirrors.py`. The CI
// step `tests/test_orm_is_source_of_truth.py::
// test_ts_type_generator_is_deterministic` enforces a clean diff
// on every PR.
//
// To add or change a field:
//
//   1. Update the SQLAlchemy model in `agent_mcp/db/models/`.
//   2. Update the Pydantic mirror in `agent_mcp/db/pydantic_mirrors.py`.
//   3. Run `python scripts/generate_ts_types.py` and commit the diff.
//
// The dashboard imports the interfaces declared here from
// `lib/api.ts`, which re-exports them under their canonical names
// (Agent, Task, ...).
"""


def _ts_type_for_schema(node: dict[str, Any], defs: dict[str, Any]) -> str:
    """Translate a single JSON-schema node to a TypeScript type."""
    if not isinstance(node, dict):
        return "unknown"

    # Pydantic emits anyOf for Optional[T]: anyOf=[{type:'X'}, {type:'null'}].
    if "anyOf" in node:
        members = [_ts_type_for_schema(m, defs) for m in node["anyOf"]]
        # Deduplicate while preserving order.
        seen: list[str] = []
        for m in members:
            if m not in seen:
                seen.append(m)
        return " | ".join(seen)

    if "$ref" in node:
        ref = node["$ref"].split("/")[-1]
        target = defs.get(ref)
        if target is not None:
            return _ts_type_for_schema(target, defs)
        return ref

    t = node.get("type")
    if t == "string":
        return "string"
    if t == "integer":
        return "number"
    if t == "number":
        return "number"
    if t == "boolean":
        return "boolean"
    if t == "null":
        return "null"
    if t == "array":
        items = node.get("items", {})
        return f"Array<{_ts_type_for_schema(items, defs)}>"
    if t == "object":
        return "Record<string, unknown>"
    return "unknown"


def _ts_field_line(
    name: str,
    schema: dict[str, Any],
    required: set[str],
    defs: dict[str, Any],
) -> str:
    ts_type = _ts_type_for_schema(schema, defs)
    # An optional field (name not in `required`) is rendered as
    # `name?: T | null` — matching the existing `lib/api.ts` style.
    # If the resolved type already includes `null` (Optional[T] which
    # Pydantic emits as anyOf=[T, null]), don't double-add it.
    if name in required:
        return f"  {name}: {ts_type}"
    if "null" in [part.strip() for part in ts_type.split("|")]:
        return f"  {name}?: {ts_type}"
    return f"  {name}?: {ts_type} | null"


def render_ts(mirrors: dict[str, Any]) -> str:
    """Render the full generated TS file as a string."""
    parts: list[str] = [HEADER, ""]

    # Sort table names so the file ordering is deterministic.
    for table_name in sorted(mirrors.keys()):
        mirror_cls = mirrors[table_name]
        interface_name = mirror_cls.__name__
        schema = mirror_cls.model_json_schema()
        properties: dict[str, Any] = schema.get("properties", {})
        required: set[str] = set(schema.get("required", []))
        defs: dict[str, Any] = schema.get("$defs", {})

        parts.append(
            f"/** Pydantic mirror of the `{table_name}` table. */"
        )
        parts.append(f"export interface {interface_name} {{")
        # `properties` preserves Pydantic declaration order in v2.
        for field_name, field_schema in properties.items():
            parts.append(_ts_field_line(field_name, field_schema, required, defs))
        parts.append("}")
        parts.append("")

    # Convenience alias map: table_name -> interface name. The
    # dashboard re-uses these via the explicit re-exports in lib/api.ts;
    # the map itself is informative only.
    parts.append("/** Table-name to interface map. */")
    parts.append("export const MIRROR_TABLE_NAMES = [")
    for table_name in sorted(mirrors.keys()):
        parts.append(f'  "{table_name}",')
    parts.append("] as const;")
    parts.append("")

    return "\n".join(parts)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Generate TS types from Pydantic mirrors."
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=REPO_ROOT
        / "agent_mcp"
        / "dashboard"
        / "lib"
        / "api-types.generated.ts",
        help="Output path (default: agent_mcp/dashboard/lib/api-types.generated.ts)",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Don't write; fail if the existing file differs from "
        "what would be generated.",
    )
    args = parser.parse_args(argv)

    # Import after sys.path is set so the script works as
    # `python scripts/generate_ts_types.py` from any cwd.
    from agent_mcp.db.pydantic_mirrors import MIRRORS

    rendered = render_ts(MIRRORS)

    if args.check:
        if not args.output.is_file():
            print(
                f"Generated file missing: {args.output}", file=sys.stderr
            )
            return 1
        existing = args.output.read_text()
        if existing != rendered:
            print(
                f"Generated TS file is out of date: {args.output}\n"
                f"Run `python scripts/generate_ts_types.py` and commit.",
                file=sys.stderr,
            )
            return 1
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(rendered)
    return 0


if __name__ == "__main__":  # pragma: no cover - entry point
    raise SystemExit(main())
