# Agent-MCP/agent_mcp/db/models/agent_message.py
"""`agent_messages` ORM model (db-review PR-G4).

Fourth model in the incremental SQLAlchemy adoption (after
`ProjectContext`, `Agent`, `Task`). The schema mirrors what
`agent_mcp.db.schema.init_database()` creates for fresh DBs —
keeping the column set + types identical means the ORM can read/write
rows on a DB that was bootstrapped by raw SQL.

The two FK constraints
(`sender_id`/`recipient_id` -> `agents.agent_id`) were declared in
migration 0008 (PR-G1) — the model does NOT carry SQLAlchemy
`ForeignKey()` annotations because that would cause SQLAlchemy to
emit FK DDL inside `create_all()`, which would conflict with the
hand-written DDL in `init_database()` / Alembic. The constraint
lives in the DB; the ORM just reads/writes through it.

Column rationale:

* `message_id`: TEXT PRIMARY KEY — `msg_<16-hex>` format generated by
  the tool/route handlers.
* `sender_id` / `recipient_id`: NOT NULL agent_ids. FK to
  `agents.agent_id` (PR-G1 / migration 0008).
* `message_content`: NOT NULL TEXT.
* `message_type` / `priority`: NOT NULL TEXT with DB-level DEFAULTs
  ('text' and 'normal' respectively). The ORM does NOT replicate the
  DEFAULT — callers always pass an explicit value, and the DEFAULT
  is purely a safety net for hand-written INSERTs.
* `timestamp`: NOT NULL ISO-8601 string.
* `delivered` / `read`: NOT NULL BOOLEAN (sqlite stores as 0/1).
"""

from __future__ import annotations

from sqlalchemy import Boolean, Index, Text, text
from sqlalchemy.orm import Mapped, mapped_column

from ..engine import Base


class AgentMessage(Base):
    __tablename__ = "agent_messages"

    message_id: Mapped[str] = mapped_column(Text, primary_key=True)
    sender_id: Mapped[str] = mapped_column(Text, nullable=False)
    recipient_id: Mapped[str] = mapped_column(Text, nullable=False)
    message_content: Mapped[str] = mapped_column(Text, nullable=False)
    message_type: Mapped[str] = mapped_column(
        Text, nullable=False, server_default=text("'text'"),
    )
    priority: Mapped[str] = mapped_column(
        Text, nullable=False, server_default=text("'normal'"),
    )
    timestamp: Mapped[str] = mapped_column(Text, nullable=False)
    delivered: Mapped[bool] = mapped_column(
        Boolean, nullable=False, server_default=text("0"),
    )
    read: Mapped[bool] = mapped_column(
        Boolean, nullable=False, server_default=text("0"),
    )

    # v5.0.22 (feat: message threads + subjects). Both nullable:
    #   * subject       — root-only summary line (replies stay NULL).
    #   * parent_message_id — self-FK; NULL = root message.
    # The FK itself (ON DELETE SET NULL) is declared in migration 0012
    # rather than via a SQLAlchemy `ForeignKey()` annotation here, for
    # the same reason `sender_id` / `recipient_id` carry no annotation:
    # `create_all()` and the migration would race on FK DDL emission.
    # The migration is idempotent and runs for fresh DBs too, so the
    # FK lands either way.
    subject: Mapped[str | None] = mapped_column(Text, nullable=True)
    parent_message_id: Mapped[str | None] = mapped_column(Text, nullable=True)

    # PR-W3 (ORM big-bang): these four indexes were previously
    # only declared in init_database()'s raw SQL. Moving them onto
    # the ORM model means Base.metadata.create_all() reproduces the
    # full canonical index set for a fresh DB.
    __table_args__ = (
        Index(
            "idx_agent_messages_recipient_timestamp",
            "recipient_id",
            "timestamp",
        ),
        Index(
            "idx_agent_messages_sender_timestamp",
            "sender_id",
            "timestamp",
        ),
        Index(
            "idx_agent_messages_unread",
            "recipient_id",
            "read",
            "timestamp",
        ),
        Index("idx_agent_messages_delivered", "delivered"),
        # v5.0.22: thread-by-root lookups. Supports
        # WHERE parent_message_id = ? for fanning out a thread.
        Index("idx_agent_messages_parent", "parent_message_id"),
    )

    def __repr__(self) -> str:  # pragma: no cover — debug aid
        return (
            f"<AgentMessage message_id={self.message_id!r} "
            f"from={self.sender_id!r} to={self.recipient_id!r}>"
        )
