# Agent-MCP/agent_mcp/db/models/mcp_session.py
"""`mcp_sessions` ORM model (db-review PR-G5).

Fifth model in the incremental SQLAlchemy adoption (after
`ProjectContext`, `Agent`, `Task`, `AgentMessage`). The schema
mirrors the canonical DDL — `init_database()` for fresh DBs plus
the Alembic migrations 0004 (table create) and 0005 (alias_used
column) — and `agent_id` has a NOT NULL FK to `agents.agent_id`
landed by migration 0008 (PR-G1).

The model declares a `relationship('Agent')` so callers can navigate
\`session.agent\` to inspect the parent row without a separate query.
The FK constraint itself lives in the DDL (init_database + Alembic)
— we do NOT add `ForeignKey()` to the column annotation because that
would cause SQLAlchemy to emit FK DDL inside `create_all()`, which
would conflict with the hand-written DDL. The `primaryjoin=` keeps
the relationship navigable without declaring the constraint twice.

Column rationale:

* `session_id`: TEXT PRIMARY KEY NOT NULL — uuid4 hex generated by
  `core.session_registry.register_session`. Independent of any
  client-provided identifier so a misbehaving client can't collide
  with someone else's stream.
* `agent_id`: NOT NULL agent_id (NOT the bearer token). FK to
  `agents.agent_id` (PR-G1 / migration 0008).
* `opened_at` / `last_seen_at`: NOT NULL ISO-8601 UTC strings.
* `bearer_token_hash`: NOT NULL sha256(bearer) — the raw bearer
  never lands on disk.
* `alias_used`: nullable; non-NULL when the stream was opened via a
  router alias URL (Phase 1c — set from the
  `X-Agent-MCP-Alias: <alias_name>,<expires_at>` header).
"""

from __future__ import annotations

from typing import Optional

from sqlalchemy import Text
from sqlalchemy.orm import Mapped, foreign, mapped_column, relationship

from ..engine import Base
from .agent import Agent


class McpSession(Base):
    __tablename__ = "mcp_sessions"

    session_id: Mapped[str] = mapped_column(Text, primary_key=True)
    agent_id: Mapped[str] = mapped_column(Text, nullable=False)
    opened_at: Mapped[str] = mapped_column(Text, nullable=False)
    last_seen_at: Mapped[str] = mapped_column(Text, nullable=False)
    bearer_token_hash: Mapped[str] = mapped_column(Text, nullable=False)
    alias_used: Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    # Many-to-one navigation to the parent Agent row. The DDL-level FK
    # was added by migration 0008 (PR-G1); we declare the join here
    # without a `ForeignKey()` annotation on the column itself so
    # SQLAlchemy doesn't try to emit FK DDL via `create_all()`.
    # `foreign(agent_id)` tells the ORM which side carries the
    # foreign-key value for join inference.
    agent: Mapped[Agent] = relationship(
        Agent,
        primaryjoin=lambda: foreign(McpSession.agent_id) == Agent.agent_id,
        viewonly=True,
        lazy="select",
    )

    def __repr__(self) -> str:  # pragma: no cover — debug aid
        return (
            f"<McpSession session_id={self.session_id!r} "
            f"agent_id={self.agent_id!r}>"
        )
