# Agent-MCP/agent_mcp/db/models/task.py
"""`tasks` ORM model (db-review PR-G3).

Third model in the incremental SQLAlchemy adoption (after
`ProjectContext` and `Agent`). The schema mirrors what
`agent_mcp.db.schema.init_database()` creates for fresh DBs —
keeping the column set + types identical means the ORM can read/write
rows on a DB that was bootstrapped by raw SQL.

This PR ships the model + parity test + a cutover of
`agent_mcp.db.actions.task_db` (the reader surface used by
lifespan startup, dashboard API, and the all-tasks route). The
tool-side writes (task_tools.py, routes.py purge cascade) keep raw
SQL for now; follow-up PRs migrate them.

Column rationale:

* `task_id`: TEXT PRIMARY KEY — `task_<16-hex>` format generated by
  `task_tools._generate_task_id`. Referenced by two FK constraints
  (PR #96): `agents.current_task` and `tasks.parent_task` (self-ref).
* `title` / `created_by` / `status` / `priority` / `created_at` /
  `updated_at`: NOT NULL — required for every task row.
* `description` / `assigned_to` / `parent_task`: nullable.
* `assigned_to`: agent_id (NOT a token) of the worker assigned to
  this task. FK to `agents.agent_id` (PR #96).
* `child_tasks` / `depends_on_tasks` / `notes`: JSON-as-TEXT,
  nullable in DDL (defaults to `"[]"` on writes from the tool
  surface). `notes` is the legacy embedded format
  `[{timestamp, author, content}, ...]` — PR-H migrates this to a
  side table while leaving the column in place for one release.
"""

from __future__ import annotations

from typing import Optional

from sqlalchemy import Text
from sqlalchemy.orm import Mapped, mapped_column

from ..engine import Base


class Task(Base):
    __tablename__ = "tasks"

    task_id: Mapped[str] = mapped_column(Text, primary_key=True)
    title: Mapped[str] = mapped_column(Text, nullable=False)
    description: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    assigned_to: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    created_by: Mapped[str] = mapped_column(Text, nullable=False)
    status: Mapped[str] = mapped_column(Text, nullable=False)
    priority: Mapped[str] = mapped_column(Text, nullable=False)
    created_at: Mapped[str] = mapped_column(Text, nullable=False)
    updated_at: Mapped[str] = mapped_column(Text, nullable=False)
    parent_task: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    child_tasks: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    depends_on_tasks: Mapped[Optional[str]] = mapped_column(
        Text, nullable=True,
    )
    notes: Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    def __repr__(self) -> str:  # pragma: no cover — debug aid
        return f"<Task task_id={self.task_id!r} status={self.status!r}>"
